### PR TITLE
Update get_ngrok.sh

### PR DESCRIPTION
**Pull request by bx70Mk**

### CODE REVIEW

**Comment by JohanAR** [comment]
I can't test it, but it looks good to me. Thanks!

**Comment by bx70Mk** [comment]
i have an error on the colab note book,.
Copy-paste to the terminal the command below and run (press Enter)

Mac:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-19-4a78138efeff>](https://localhost:8080/#) in <cell line: 3>()
      1 print('Copy-paste to the terminal the command below and run (press Enter)\n')
      2 print('Mac:')
----> 3 print(f'./run_mac.sh --is-client --in-addr {in_addr} --out-addr {out_addr}')
      4 print('\nWindows:')
      5 print(f'run_windows.bat --is-client --in-addr {in_addr} --out-addr {out_addr}')

NameError: name 'in_addr' is not defined 

i think it has something withthe ngrok version in the repo. Or do you have an idea on how i can solve this issue?

**Comment by bx70Mk** [comment]
okay, i dont run it locally cuz my hardware dosent support. colab is like an easy way to run it without stressing my hardware. when i run all the cells in colab i ge the ngrok error 121 saying the ngrok version is outdated i need to upgrade. but unfortunately i cant upgrade it cuz theres no access to the repo only admin. I tried forking and creating a new colab with my own repo but theres issues relating to permissions and othere thats stressing me out. is there a way i can contact the main author?

**Comment by JohanAR** [comment]
Well I did accept your pull request since I have permission to do that, so it's in the repo now.

Unfortunately there's no way to contact alievk. I think this was more or less a quick experiment he created and then decided to share with others, but eventually moved on to other projects.

**Comment by Ndumatt1** [comment]
I tried running it using colab, still no progress in  the ngrok version, ngrok still wants upgrading

**Comment by Ndumatt1** [comment]
I didnt upgrade it, Its printing something went wrong, This is the error message Opening tunnel
start - start tunnels by name from the configuration file

USAGE:
  ngrok start [flags]

AUTHOR:
  ngrok - <[support@ngrok.com](mailto:support@ngrok.com)>

COMMANDS: 
  config          update or migrate ngrok's configuration file
  http            start an HTTP tunnel
  tcp             start a TCP tunnel
  tunnel          start a tunnel for use with a tunnel-group backen

EXAMPLES: 
  ngrok http 80                                                 # secure public URL for port 80 web server
  ngrok http --domain baz.ngrok.dev 8080                        # port 8080 available at baz.ngrok.dev
  ngrok tcp 22                                                  # tunnel arbitrary TCP traffic to port 22
  ngrok http 80 --oauth=google --[oauth-allow-email=foo@foo.com](mailto:oauth-allow-email=foo@foo.com)  # secure your app with oauth

Paid Features: 
  ngrok http 80 --domain mydomain.com                           # run ngrok with your own custom domain
  ngrok http 80 --allow-cidr 2600:8c00::a03c:91ee:fe69:9695/32  # run ngrok with IP policy restrictions
  Upgrade your account at https://dashboard.ngrok.com/billing/subscription to access paid features

Upgrade your account at https://dashboard.ngrok.com/billing/subscription to access paid features

Flags:
  -h, --help      help for ngrok

Use "ngrok [command] --help" for more information about a command.
Something went wrong, reopen the tunnel

**Comment by Ndumatt1** [comment]
If you are available now so we can troubleshoot it, that would be great

**Comment by Ndumatt1** [comment]
If you are available now so we can troubleshoot it, that would be great

**Comment by bx70Mk** [comment]
okay 
we can work on it now

**Comment by Ndumatt1** [comment]
I think we need to schedule it

**Comment by bx70Mk** [comment]
to when?

**Comment by Ndumatt1** [comment]
Not sure where you are located, but maybe in the afternoon today? If we should start now, I have limited battery as I don't have electricity currently

**Pull request merged**
